name: sentinel

services:
  rincon:
    container_name: sentinel-rincon
    image: bk1031/rincon:latest
    restart: always
    ports:
      - "10311:10311"
    depends_on:
      - db
    environment:
      STORAGE_MODE: sql
      DB_DRIVER: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: sentinel

  core:
    container_name: sentinel-core
    image: golang:1.26-alpine
    restart: always
    working_dir: /app
    command: >
      sh -c "go install github.com/air-verse/air@latest && air"
    volumes:
      - ./core:/app
      - core_gopath:/go
    ports:
      - "9999:9999"
    depends_on:
      - db
      - rincon
    environment:
      ENV: DEV
      PORT: 9999
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: password
      DATABASE_NAME: sentinel
      RINCON_ENDPOINT: http://rincon:10311
      RINCON_USER: admin
      RINCON_PASSWORD: admin
      SERVICE_ENDPOINT: http://core:9999
      SERVICE_HEALTH_CHECK: http://core:9999/core/ping

  discord:
    container_name: sentinel-discord
    image: golang:1.26-alpine
    restart: always
    working_dir: /app
    command: >
      sh -c "go install github.com/air-verse/air@latest && air"
    volumes:
      - ./discord:/app
      - discord_gopath:/go
    ports:
      - "9998:9998"
    depends_on:
      - db
      - rincon
    environment:
      ENV: DEV
      PORT: 9998
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: password
      DATABASE_NAME: sentinel
      RINCON_ENDPOINT: http://rincon:10311
      RINCON_USER: admin
      RINCON_PASSWORD: admin
      SERVICE_ENDPOINT: http://discord:9998
      SERVICE_HEALTH_CHECK: http://discord:9998/discord/ping
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      DISCORD_GUILD: ${DISCORD_GUILD}
      DISCORD_PREFIX: d!

  oauth:
    container_name: sentinel-oauth
    image: golang:1.26-alpine
    restart: always
    working_dir: /app
    command: >
      sh -c "go install github.com/air-verse/air@latest && air"
    volumes:
      - ./oauth:/app
      - oauth_gopath:/go
    ports:
      - "9997:9997"
    depends_on:
      - db
      - rincon
    environment:
      ENV: DEV
      PORT: 9997
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: password
      DATABASE_NAME: sentinel
      RINCON_ENDPOINT: http://rincon:10311
      RINCON_USER: admin
      RINCON_PASSWORD: admin
      SERVICE_ENDPOINT: http://oauth:9997
      SERVICE_HEALTH_CHECK: http://oauth:9997/oauth/ping

  db:
    container_name: sentinel-db
    image: postgres:18-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sentinel
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  core_gopath:
  discord_gopath:
  oauth_gopath:
