ENV=DEV
PORT=9999
PREFIX="d!"

POSTGRES_HOST=localhost
POSTGRES_USER=postgres
POSTGRES_PASSWORD=postgres
POSTGRES_PORT=5432
EXTERNAL_POSTGRES_PORT=5432

AUTH_SIGNING_KEY="wMGxEdWYBo3dCb5e0Tzu3qxNCsfYePCM"