name: tests
run-name: Triggered by ${{ github.event_name }} to ${{ github.ref }} by @${{ github.actor }}

on: [push]

jobs:
    web_lint_check:
        runs-on: ubuntu-latest
        name: web lint
        defaults:
            run:
                shell: bash
                working-directory: ./web
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                submodules: true
            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                node-version: '22.x'
            - name: Install dependencies
              run: |
                npm ci
            - name: Run lint
              run: |
                npm run lint
            - name: Run Check
              run: |
                npm run check
