name: tests
run-name: Triggered by ${{ github.event_name }} to ${{ github.ref }} by @${{ github.actor }}

on: [push]

jobs:
    go_unit_test:
        runs-on: ubuntu-latest
        name: unit
        defaults:
            run:
                shell: bash
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                submodules: true
            - name: Setup Go
              uses: actions/setup-go@v4
              with:
                go-version: '1.22.0'
            - name: Install dependencies
              run: |
                go get .
            - name: Run tests
              run: |
                make test
            - name: Upload coverage to Codecov
              uses: codecov/codecov-action@v3
              env:
                CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
              with:
                files: coverage.out
                verbose: true

    web_lint_check:
        runs-on: ubuntu-latest
        name: web lint
        defaults:
            run:
                shell: bash
                working-directory: ./web
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                submodules: true
            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                node-version: '22.x'
            - name: Install dependencies
              run: |
                npm ci
            - name: Run lint
              run: |
                npm run lint
            - name: Run Check
              run: |
                npm run check
